language: node_js

node_js:
  - "v11.1.0"
  - "v11.0.0"
  - "v10.0.0"

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - node scripts/buildall.js
