name: main

on: push

jobs:
  build:
    strategy:
      matrix:
        config:
        - node-version: '10.13.0'
          NO_LINT: 1
        - node-version: '14.16.0'
        - node-version: '15.12.0'

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.config.node-version }}

    - run: yarn install --frozen-lockfile
    - run: yarn workspaces run clean
    - run: yarn workspaces run build
    - run: yarn workspaces run lint
      if: matrix.config.NO_LINT != 1
    - run: yarn workspaces run test
